#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

require __DIR__ . '/bootstrap/constants.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/bootstrap/functions.php';

$config = require __DIR__ . '/config/base/console.php';
$app = new yii\console\Application($config);

$exitCode = $app->run();
exit($exitCode);
